#!/usr/bin/env perl
use strict;
use warnings;
use JSON::PP;
use File::Basename qw(dirname);
use File::Temp qw(tempfile);
my ($input, @outputs) = @ARGV;
die "Usage: perl generate-geo-prefix.pl /spider/local_data/prefix_data.pl /spider/dxweb/public/geo-prefix.json /spider/dxweb-admin/admin/geo-prefix.json\n" unless $input && @outputs;
die "Missing prefix data: $input\n" unless -f $input;
# The file is a Perl data dump generated by create_prefix.pl. Evaluate only the
# locally trusted, operator-maintained DXSpider file, never network/user input.
{
    package DXGeoPrefixData;
    our (%pre, %prefix_loc);
    my $ok = do $input;
    die "Cannot load $input: $@ $!\n" unless $ok;
}
my %prefixes;
while (my ($key, $ids) = each %DXGeoPrefixData::pre) {
    next unless $key =~ /\A=?[A-Z0-9\/]+\z/;
    my ($id) = split /,/, $ids;
    my $record = $DXGeoPrefixData::prefix_loc{$id};
    next unless ref($record) eq 'Prefix';
    my ($lat,$lon) = @{$record}{qw(lat long)};
    next unless defined($lat) && defined($lon) && $lat =~ /\A-?\d+(?:\.\d+)?\z/ && $lon =~ /\A-?\d+(?:\.\d+)?\z/;
    next if abs($lat)>90 || abs($lon)>180;
    $prefixes{$key} = [0+$lat,0+$lon];
}
die "No valid prefixes from $input\n" unless keys(%prefixes) > 100;
my $json=JSON::PP->new->canonical->encode({version=>1,prefixes=>\%prefixes});
for my $output (@outputs) {
    my ($fh,$tmp)=tempfile('.geo-prefix-XXXXXX',DIR=>dirname($output),UNLINK=>0);
    binmode($fh,':raw'); print {$fh} $json or die "Write $tmp: $!";
    close $fh or die "Close $tmp: $!";
    chmod 0644,$tmp;
    rename($tmp,$output) or die "Rename $tmp -> $output: $!";
    print "$output: ",scalar(keys %prefixes)," prefix entries\n";
}
